"""
Seed default roles and permissions for RBAC system.
"""
from app import create_app
from models import db, Role

def seed_roles():
    """Seed default roles with permissions."""
    app = create_app()
    
    with app.app_context():
        # Default roles with permissions
        default_roles = [
            {
                "name": "Admin",
                "permissions": {
                    "events": True,
                    "clients": True,
                    "inventory": True,
                    "catering": True,
                    "bakery": True,
                    "hire": True,
                    "procurement": True,
                    "production": True,
                    "finance": True,
                    "hr": True,
                    "reports": True,
                    "bi": True,
                    "pos": True,
                    "food_safety": True,
                    "haccp": True,
                    "dispatch": True,
                    "admin": True,
                    "communication": True,
                    "tasks": True,
                    "quotes": True,
                    "invoices": True,
                    "accounting": True,
                    "crm": True,
                    "leads": True,
                    "vendors": True,
                    "contracts": True,
                    "menu_builder": True,
                    "timeline": True,
                    "automation": True,
                    "integrations": True,
                    "university": True,
                    "chat": True,
                    "audit": True,
                    "kds": True,
                    "mobile_staff": True,
                    "incidents": True,
                    "branches": True,
                    "floorplanner": True,
                    "proposals": True,
                    "profitability": True,
                    "production_recipes": True,
                    "search": True,
                }
            },
            {
                "name": "Manager",
                "permissions": {
                    "events": True,
                    "clients": True,
                    "inventory": True,
                    "catering": True,
                    "bakery": True,
                    "hire": True,
                    "procurement": True,
                    "production": True,
                    "finance": False,
                    "hr": True,
                    "reports": True,
                    "bi": True,
                    "pos": True,
                    "food_safety": True,
                    "haccp": True,
                    "dispatch": True,
                    "admin": False,
                    "communication": True,
                    "tasks": True,
                    "quotes": True,
                    "invoices": True,
                    "accounting": False,
                    "crm": True,
                    "leads": True,
                    "vendors": True,
                    "contracts": True,
                    "menu_builder": True,
                    "timeline": True,
                    "automation": False,
                    "integrations": False,
                    "university": True,
                    "chat": True,
                    "audit": True,
                    "kds": True,
                    "mobile_staff": True,
                    "incidents": True,
                    "branches": True,
                    "floorplanner": True,
                    "proposals": True,
                    "profitability": True,
                    "production_recipes": True,
                    "search": True,
                }
            },
            {
                "name": "Procurement",
                "permissions": {
                    "events": False,
                    "clients": False,
                    "inventory": True,
                    "catering": False,
                    "bakery": False,
                    "hire": False,
                    "procurement": True,
                    "production": False,
                    "finance": False,
                    "hr": False,
                    "reports": False,
                    "bi": False,
                    "pos": False,
                    "food_safety": False,
                    "haccp": False,
                    "dispatch": False,
                    "admin": False,
                    "communication": False,
                    "tasks": True,
                    "quotes": False,
                    "invoices": False,
                    "accounting": False,
                    "crm": False,
                    "leads": False,
                    "vendors": True,
                    "contracts": False,
                    "menu_builder": False,
                    "timeline": False,
                    "automation": False,
                    "integrations": False,
                    "university": False,
                    "chat": False,
                    "audit": False,
                    "kds": False,
                    "mobile_staff": False,
                    "incidents": False,
                    "branches": False,
                    "floorplanner": False,
                    "proposals": False,
                    "profitability": False,
                    "production_recipes": False,
                    "search": True,
                }
            },
            {
                "name": "Chef",
                "permissions": {
                    "events": True,
                    "clients": False,
                    "inventory": True,
                    "catering": True,
                    "bakery": True,
                    "hire": False,
                    "procurement": False,
                    "production": True,
                    "finance": False,
                    "hr": False,
                    "reports": False,
                    "bi": False,
                    "pos": False,
                    "food_safety": True,
                    "haccp": True,
                    "dispatch": False,
                    "admin": False,
                    "communication": True,
                    "tasks": True,
                    "quotes": False,
                    "invoices": False,
                    "accounting": False,
                    "crm": False,
                    "leads": False,
                    "vendors": False,
                    "contracts": False,
                    "menu_builder": True,
                    "timeline": True,
                    "automation": False,
                    "integrations": False,
                    "university": False,
                    "chat": True,
                    "audit": False,
                    "kds": True,
                    "mobile_staff": False,
                    "incidents": True,
                    "branches": False,
                    "floorplanner": False,
                    "proposals": False,
                    "profitability": False,
                    "production_recipes": True,
                    "search": True,
                }
            },
            {
                "name": "Dispatcher",
                "permissions": {
                    "events": True,
                    "clients": False,
                    "inventory": False,
                    "catering": False,
                    "bakery": False,
                    "hire": True,
                    "procurement": False,
                    "production": False,
                    "finance": False,
                    "hr": False,
                    "reports": False,
                    "bi": False,
                    "pos": False,
                    "food_safety": False,
                    "haccp": False,
                    "dispatch": True,
                    "admin": False,
                    "communication": True,
                    "tasks": True,
                    "quotes": False,
                    "invoices": False,
                    "accounting": False,
                    "crm": False,
                    "leads": False,
                    "vendors": False,
                    "contracts": False,
                    "menu_builder": False,
                    "timeline": True,
                    "automation": False,
                    "integrations": False,
                    "university": False,
                    "chat": True,
                    "audit": False,
                    "kds": False,
                    "mobile_staff": True,
                    "incidents": True,
                    "branches": True,
                    "floorplanner": False,
                    "proposals": False,
                    "profitability": False,
                    "production_recipes": False,
                    "search": True,
                }
            },
            {
                "name": "Finance",
                "permissions": {
                    "events": True,
                    "clients": True,
                    "inventory": False,
                    "catering": False,
                    "bakery": False,
                    "hire": False,
                    "procurement": False,
                    "production": False,
                    "finance": True,
                    "hr": False,
                    "reports": True,
                    "bi": True,
                    "pos": True,
                    "food_safety": False,
                    "haccp": False,
                    "dispatch": False,
                    "admin": False,
                    "communication": False,
                    "tasks": True,
                    "quotes": True,
                    "invoices": True,
                    "accounting": True,
                    "crm": False,
                    "leads": False,
                    "vendors": False,
                    "contracts": True,
                    "menu_builder": False,
                    "timeline": False,
                    "automation": False,
                    "integrations": False,
                    "university": False,
                    "chat": False,
                    "audit": True,
                    "kds": False,
                    "mobile_staff": False,
                    "incidents": False,
                    "branches": False,
                    "floorplanner": False,
                    "proposals": True,
                    "profitability": True,
                    "production_recipes": False,
                    "search": True,
                }
            },
            {
                "name": "HACCP",
                "permissions": {
                    "events": False,
                    "clients": False,
                    "inventory": True,
                    "catering": False,
                    "bakery": False,
                    "hire": False,
                    "procurement": False,
                    "production": True,
                    "finance": False,
                    "hr": False,
                    "reports": False,
                    "bi": False,
                    "pos": False,
                    "food_safety": True,
                    "haccp": True,
                    "dispatch": False,
                    "admin": False,
                    "communication": False,
                    "tasks": True,
                    "quotes": False,
                    "invoices": False,
                    "accounting": False,
                    "crm": False,
                    "leads": False,
                    "vendors": False,
                    "contracts": False,
                    "menu_builder": False,
                    "timeline": False,
                    "automation": False,
                    "integrations": False,
                    "university": False,
                    "chat": False,
                    "audit": False,
                    "kds": False,
                    "mobile_staff": False,
                    "incidents": True,
                    "branches": False,
                    "floorplanner": False,
                    "proposals": False,
                    "profitability": False,
                    "production_recipes": False,
                    "search": True,
                }
            },
            {
                "name": "Staff",
                "permissions": {
                    "events": False,
                    "clients": False,
                    "inventory": False,
                    "catering": False,
                    "bakery": False,
                    "hire": False,
                    "procurement": False,
                    "production": False,
                    "finance": False,
                    "hr": False,
                    "reports": False,
                    "bi": False,
                    "pos": True,
                    "food_safety": False,
                    "haccp": False,
                    "dispatch": False,
                    "admin": False,
                    "communication": True,
                    "tasks": True,
                    "quotes": False,
                    "invoices": False,
                    "accounting": False,
                    "crm": False,
                    "leads": False,
                    "vendors": False,
                    "contracts": False,
                    "menu_builder": False,
                    "timeline": False,
                    "automation": False,
                    "integrations": False,
                    "university": True,
                    "chat": True,
                    "audit": False,
                    "kds": True,
                    "mobile_staff": True,
                    "incidents": True,
                    "branches": False,
                    "floorplanner": False,
                    "proposals": False,
                    "profitability": False,
                    "production_recipes": False,
                    "search": False,
                }
            }
        ]
        
        created = 0
        for role_data in default_roles:
            existing = Role.query.filter_by(name=role_data["name"]).first()
            if not existing:
                role = Role(**role_data)
                db.session.add(role)
                created += 1
            else:
                # Update existing role permissions
                existing.permissions = role_data["permissions"]
        
        try:
            db.session.commit()
            print(f"✅ Successfully seeded {created} new roles and updated existing roles!")
            print(f"   Roles: {', '.join([r['name'] for r in default_roles])}")
        except Exception as e:
            db.session.rollback()
            print(f"❌ Error seeding roles: {e}")
            raise

if __name__ == "__main__":
    seed_roles()

