"""
SAS AI Knowledge Base - Comprehensive system knowledge and module descriptions.
"""
SYSTEM_KNOWLEDGE = {
    "system": (
        "The SAS Management System is a comprehensive business management platform.\n\n"
        "**Core Modules:**\n"
        "• Event Service - Event planning and execution\n"
        "• Accounting - Financial management and reporting\n"
        "• Production - Kitchen operations and food preparation\n"
        "• Inventory - Stock and ingredient management\n"
        "• HR/Staff - Workforce management\n"
        "• Bakery - Baked goods production\n"
        "• POS - Point of sale system\n"
        "• Analytics - Business intelligence and insights\n"
        "\n"
        "**Supporting Modules:**\n"
        "• CRM - Customer relationship management\n"
        "• Vendors - Vendor management\n"
        "• Venues - Event location management\n"
        "• Reports - Comprehensive reporting\n"
        "• Automation - Workflow automation\n"
        "• Integrations - Third-party integrations\n"
        "\n"
        "All modules work together to provide end-to-end business control."
    ),
    "inventory": (
        "The Inventory module manages all stock, supplies, and ingredients.\n\n"
        "**Key Features:**\n"
        "• Item quantities and locations tracking\n"
        "• Low-stock alerts and reorder points\n"
        "• Ingredient availability for production\n"
        "• Stock movements and transaction history\n"
        "• Category-based organization\n"
        "• SKU and barcode management\n"
        "• Cost tracking and valuation\n"
        "\n"
        "**Integration:** Works with Production, Events, Bakery, and POS modules to track usage and maintain stock levels."
    ),
    "accounting": (
        "The Accounting module provides comprehensive financial management.\n\n"
        "**Key Features:**\n"
        "• Double-entry bookkeeping system\n"
        "• Chart of Accounts management\n"
        "• Invoice creation and tracking\n"
        "• Payment recording and receipts\n"
        "• Journal entries and general ledger\n"
        "• Bank reconciliation\n"
        "• Trial balance and financial reports\n"
        "• Event profitability analysis\n"
        "• Payroll integration\n"
        "• Cashbook management\n"
        "\n"
        "**Integration:** Receives data from Events, Production, POS, and Bakery modules to provide complete financial visibility."
    ),
    "production": (
        "The Production module manages kitchen operations and food preparation.\n\n"
        "**Key Features:**\n"
        "• Production order creation and management\n"
        "• Recipe management with scaling capabilities\n"
        "• Ingredient reservation and tracking\n"
        "• Production scheduling (prep, cook, pack, load)\n"
        "• Production sheets and task lists\n"
        "• Cost of goods (COGS) calculation\n"
        "• Quality control tracking\n"
        "• Team assignment and coordination\n"
        "• Integration with events for catering orders\n"
        "\n"
        "**Workflow:** Events create production orders → Recipes are scaled → Ingredients are reserved → Production tasks are executed → Costs are tracked → Data flows to Accounting."
    ),
    "events": (
        "The Event Service module manages events from initial planning to completion.\n\n"
        "**Key Features:**\n"
        "• Event creation and scheduling\n"
        "• Venue selection and assignment\n"
        "• Vendor management and assignment\n"
        "• Staff allocation and scheduling\n"
        "• Service orders and costing\n"
        "• Quotations and proposals\n"
        "• Timeline management\n"
        "• Checklists and task tracking\n"
        "• Document management\n"
        "• Cost tracking and profit calculation\n"
        "• Event analytics and reporting\n"
        "• Client communication\n"
        "\n"
        "**Integration:** Events coordinate with Venues, Staff, Inventory, Production, and Accounting to deliver complete event management."
    ),
    "revenue": (
        "Revenue tracking provides comprehensive income visibility.\n\n"
        "**Sources:**\n"
        "• Event payments and deposits\n"
        "• Invoice receipts\n"
        "• POS sales transactions\n"
        "• Bakery sales\n"
        "• Service charges and fees\n"
        "\n"
        "**Features:**\n"
        "• Real-time revenue tracking\n"
        "• Revenue by source analysis\n"
        "• Profit calculations\n"
        "• Revenue forecasting\n"
        "• Payment method tracking\n"
        "\n"
        "**Integration:** Aggregates data from Events, Accounting, POS, and Bakery modules."
    ),
    "staff": (
        "The HR/Staff module manages your workforce comprehensively.\n\n"
        "**Key Features:**\n"
        "• Employee records and profiles\n"
        "• Attendance tracking\n"
        "• Shift scheduling and management\n"
        "• Role and permission management\n"
        "• Payroll integration\n"
        "• Performance tracking\n"
        "• Training and certification tracking\n"
        "• Mobile staff app integration\n"
        "\n"
        "**Integration:** Staff assignments flow to Events and Production. Payroll data integrates with Accounting."
    ),
    "bakery": (
        "The Bakery module manages baked goods production and sales.\n\n"
        "**Key Features:**\n"
        "• Bakery item catalog management\n"
        "• Recipe and ingredient management\n"
        "• Production planning for baked goods\n"
        "• Order fulfillment tracking\n"
        "• Sales tracking and reporting\n"
        "• Cost tracking per item\n"
        "• Integration with inventory for ingredients\n"
        "• Integration with events for catering orders\n"
        "\n"
        "**Workflow:** Recipes defined → Ingredients reserved → Production scheduled → Items baked → Orders fulfilled → Sales recorded in Accounting."
    ),
    "pos": (
        "The POS (Point of Sale) system handles retail and counter sales.\n\n"
        "**Key Features:**\n"
        "• Order creation and management\n"
        "• Payment processing (cash, card, mobile)\n"
        "• Receipt generation\n"
        "• Shift management\n"
        "• Inventory integration (real-time stock updates)\n"
        "• Kitchen display system (KDS) integration\n"
        "• Sales reporting and analytics\n"
        "• Z-reports and end-of-day reconciliation\n"
        "• Offline mode support\n"
        "\n"
        "**Integration:** Sales flow to Accounting. Inventory is updated in real-time. Production receives kitchen tickets."
    ),
    "crm": (
        "The CRM (Customer Relationship Management) module manages customer interactions.\n\n"
        "**Key Features:**\n"
        "• Customer database and profiles\n"
        "• Lead management and tracking\n"
        "• Sales pipeline management\n"
        "• Customer communication history\n"
        "• Follow-up reminders\n"
        "• Customer segmentation\n"
        "• Integration with Events for customer event history\n"
        "\n"
        "**Integration:** Links customers to Events, Invoices, and Proposals."
    ),
    "vendors": (
        "The Vendors module manages supplier relationships.\n\n"
        "**Key Features:**\n"
        "• Vendor database and profiles\n"
        "• Contact information management\n"
        "• Purchase order tracking\n"
        "• Vendor performance evaluation\n"
        "• Contract management\n"
        "• Payment tracking\n"
        "\n"
        "**Integration:** Vendors are assigned to Events. Purchases flow to Inventory and Accounting."
    ),
    "venues": (
        "The Venues module manages event locations.\n\n"
        "**Key Features:**\n"
        "• Venue registration and profiles\n"
        "• Capacity and facility details\n"
        "• Availability tracking\n"
        "• Venue assignment to events\n"
        "• Location and contact information\n"
        "• Venue-specific requirements\n"
        "\n"
        "**Integration:** Venues are assigned to Events. Venue costs are tracked in Accounting."
    ),
    "reports": (
        "The Reports module provides comprehensive business reporting.\n\n"
        "**Report Types:**\n"
        "• Financial reports (P&L, balance sheet, cash flow)\n"
        "• Event performance reports\n"
        "• Production efficiency reports\n"
        "• Inventory reports\n"
        "• Sales reports\n"
        "• Staff performance reports\n"
        "• Custom report generation\n"
        "\n"
        "**Integration:** Aggregates data from all modules to provide business insights."
    ),
    "analytics": (
        "The Analytics module provides business intelligence and insights.\n\n"
        "**Features:**\n"
        "• Dashboard with key metrics\n"
        "• Revenue analytics\n"
        "• Event performance analysis\n"
        "• Production efficiency metrics\n"
        "• Inventory turnover analysis\n"
        "• Customer analytics\n"
        "• Trend analysis and forecasting\n"
        "• Custom analytics queries\n"
        "\n"
        "**Integration:** Analyzes data from all modules to provide actionable insights."
    ),
    "automation": (
        "The Automation module enables workflow automation.\n\n"
        "**Features:**\n"
        "• Automated task creation\n"
        "• Workflow triggers and rules\n"
        "• Scheduled reports\n"
        "• Notification automation\n"
        "• Data synchronization\n"
        "• Integration automation\n"
        "\n"
        "**Integration:** Automates processes across all modules to improve efficiency."
    ),
    "integrations": (
        "The Integrations module connects external systems.\n\n"
        "**Features:**\n"
        "• Third-party API integrations\n"
        "• Payment gateway integration\n"
        "• Accounting software integration\n"
        "• Email and SMS integration\n"
        "• Calendar synchronization\n"
        "• Data import/export\n"
        "\n"
        "**Integration:** Enables seamless data flow between SAS and external systems."
    ),
    "cashbook": (
        "The Cashbook module tracks cash transactions.\n\n"
        "**Features:**\n"
        "• Cash receipts and payments\n"
        "• Cash balance tracking\n"
        "• Petty cash management\n"
        "• Cash reconciliation\n"
        "• Cash flow reporting\n"
        "\n"
        "**Integration:** Part of Accounting module, tracks all cash-based transactions."
    ),
    "invoices": (
        "The Invoices module manages billing and invoicing.\n\n"
        "**Features:**\n"
        "• Invoice creation and management\n"
        "• Invoice templates\n"
        "• Payment tracking\n"
        "• Outstanding balance tracking\n"
        "• Invoice numbering and sequencing\n"
        "• PDF generation\n"
        "\n"
        "**Integration:** Links to Events and Accounting. Payments recorded in Accounting module."
    ),
    "quotes": (
        "The Quotes module manages quotations and estimates.\n\n"
        "**Features:**\n"
        "• Quote creation and management\n"
        "• Quote templates\n"
        "• Quote approval workflow\n"
        "• Quote-to-invoice conversion\n"
        "• Quote tracking and follow-up\n"
        "\n"
        "**Integration:** Quotes are created for Events and can be converted to Invoices."
    ),
    "proposals": (
        "The Proposals module manages business proposals.\n\n"
        "**Features:**\n"
        "• Proposal creation and templates\n"
        "• Proposal versioning\n"
        "• Proposal approval workflow\n"
        "• Client presentation\n"
        "• Proposal tracking\n"
        "\n"
        "**Integration:** Proposals are linked to Events and CRM for customer management."
    ),
    "profitability": (
        "The Profitability module analyzes business profitability.\n\n"
        "**Features:**\n"
        "• Event profitability analysis\n"
        "• Product profitability\n"
        "• Service profitability\n"
        "• Cost analysis\n"
        "• Margin calculations\n"
        "• Profit trend analysis\n"
        "\n"
        "**Integration:** Analyzes data from Events, Production, Accounting, and Inventory."
    ),
    "kds": (
        "The KDS (Kitchen Display System) module manages kitchen operations.\n\n"
        "**Features:**\n"
        "• Order display in kitchen\n"
        "• Order status tracking\n"
        "• Preparation time management\n"
        "• Kitchen workflow optimization\n"
        "• Integration with POS\n"
        "\n"
        "**Integration:** Receives orders from POS and sends updates to Production module."
    ),
    "menu_builder": (
        "The Menu Builder module creates and manages menus.\n\n"
        "**Features:**\n"
        "• Menu creation and editing\n"
        "• Menu item management\n"
        "• Pricing management\n"
        "• Menu templates\n"
        "• Menu versioning\n"
        "• Menu assignment to events\n"
        "\n"
        "**Integration:** Menus are used in Events, Production, and POS modules."
    ),
    "catering": (
        "The Catering module manages catering operations.\n\n"
        "**Features:**\n"
        "• Catering menu management\n"
        "• Catering order processing\n"
        "• Delivery scheduling\n"
        "• Catering-specific workflows\n"
        "\n"
        "**Integration:** Works with Events, Production, and Inventory modules."
    ),
    "dispatch": (
        "The Dispatch module manages delivery and logistics.\n\n"
        "**Features:**\n"
        "• Delivery scheduling\n"
        "• Route optimization\n"
        "• Driver assignment\n"
        "• Delivery tracking\n"
        "• Delivery confirmation\n"
        "\n"
        "**Integration:** Handles deliveries for Events, Production, and Bakery orders."
    ),
    "timeline": (
        "The Timeline module provides visual event timelines.\n\n"
        "**Features:**\n"
        "• Event timeline visualization\n"
        "• Task scheduling\n"
        "• Milestone tracking\n"
        "• Timeline editing\n"
        "\n"
        "**Integration:** Integrated with Events module for timeline management."
    ),
    "tasks": (
        "The Tasks module manages task tracking.\n\n"
        "**Features:**\n"
        "• Task creation and assignment\n"
        "• Task status tracking\n"
        "• Task priorities\n"
        "• Task deadlines\n"
        "• Task completion tracking\n"
        "\n"
        "**Integration:** Tasks are created from Events, Production, and other modules."
    ),
    "communication": (
        "The Communication module manages internal and external communications.\n\n"
        "**Features:**\n"
        "• Message management\n"
        "• Email integration\n"
        "• SMS notifications\n"
        "• Communication history\n"
        "• Team messaging\n"
        "\n"
        "**Integration:** Used across all modules for notifications and communications."
    ),
    "client_portal": (
        "The Client Portal provides customer self-service.\n\n"
        "**Features:**\n"
        "• Client login and access\n"
        "• Event viewing and updates\n"
        "• Invoice viewing and payment\n"
        "• Document access\n"
        "• Communication with staff\n"
        "\n"
        "**Integration:** Connects clients to Events, Invoices, and Communication modules."
    ),
    "mobile_staff": (
        "The Mobile Staff module provides mobile access for staff.\n\n"
        "**Features:**\n"
        "• Mobile app for staff\n"
        "• Task viewing and updates\n"
        "• Time tracking\n"
        "• Event information access\n"
        "• Real-time updates\n"
        "\n"
        "**Integration:** Connects staff to Events, Production, and HR modules."
    ),
    "food_safety": (
        "The Food Safety module manages food safety compliance.\n\n"
        "**Features:**\n"
        "• Food safety checklists\n"
        "• Temperature tracking\n"
        "• Compliance reporting\n"
        "• Training records\n"
        "• Incident tracking\n"
        "\n"
        "**Integration:** Tracks safety data for Production and Events."
    ),
    "incidents": (
        "The Incidents module tracks and manages incidents.\n\n"
        "**Features:**\n"
        "• Incident reporting\n"
        "• Incident investigation\n"
        "• Resolution tracking\n"
        "• Incident analytics\n"
        "\n"
        "**Integration:** Links incidents to Events, Production, and Food Safety modules."
    ),
    "floorplanner": (
        "The Floorplanner module manages event floor plans.\n\n"
        "**Features:**\n"
        "• Floor plan creation\n"
        "• Seating arrangements\n"
        "• Table assignments\n"
        "• Visual floor plan editor\n"
        "\n"
        "**Integration:** Floor plans are assigned to Events."
    ),
    "university": (
        "The University module manages training and education.\n\n"
        "**Features:**\n"
        "• Training courses\n"
        "• Certification tracking\n"
        "• Learning management\n"
        "• Compliance training\n"
        "\n"
        "**Integration:** Links to HR/Staff for employee training records."
    ),
    "payroll": (
        "The Payroll module manages employee compensation.\n\n"
        "**Features:**\n"
        "• Payroll calculation\n"
        "• Salary management\n"
        "• Deductions and benefits\n"
        "• Payroll reports\n"
        "• Tax calculations\n"
        "\n"
        "**Integration:** Integrates with HR/Staff and Accounting modules."
    ),
    "search": (
        "The Search module provides system-wide search functionality.\n\n"
        "**Features:**\n"
        "• Global search across modules\n"
        "• Advanced search filters\n"
        "• Search history\n"
        "• Quick access to records\n"
        "\n"
        "**Integration:** Searches across all modules and data."
    ),
    "audit": (
        "The Audit module tracks system changes and access.\n\n"
        "**Features:**\n"
        "• Change tracking\n"
        "• Access logs\n"
        "• Audit reports\n"
        "• Compliance tracking\n"
        "\n"
        "**Integration:** Monitors all modules for audit compliance."
    ),
    "branches": (
        "The Branches module manages multiple business locations.\n\n"
        "**Features:**\n"
        "• Branch management\n"
        "• Multi-location support\n"
        "• Branch-specific data\n"
        "• Cross-branch reporting\n"
        "\n"
        "**Integration:** All modules support multi-branch operations."
    ),
    "contracts": (
        "The Contracts module manages business contracts.\n\n"
        "**Features:**\n"
        "• Contract creation and storage\n"
        "• Contract templates\n"
        "• Contract tracking\n"
        "• Renewal reminders\n"
        "\n"
        "**Integration:** Contracts link to Events, Vendors, and CRM."
    ),
    "leads": (
        "The Leads module manages sales leads.\n\n"
        "**Features:**\n"
        "• Lead capture and tracking\n"
        "• Lead qualification\n"
        "• Lead conversion\n"
        "• Lead analytics\n"
        "\n"
        "**Integration:** Leads convert to Events and CRM opportunities."
    ),
    "production_recipes": (
        "The Production Recipes module manages recipe library.\n\n"
        "**Features:**\n"
        "• Recipe database\n"
        "• Recipe scaling\n"
        "• Ingredient lists\n"
        "• Cost calculations\n"
        "\n"
        "**Integration:** Recipes are used in Production and Bakery modules."
    ),
    "hire": (
        "The Hire module manages equipment and item rentals.\n\n"
        "**Features:**\n"
        "• Equipment catalog\n"
        "• Rental orders\n"
        "• Availability tracking\n"
        "• Rental pricing\n"
        "\n"
        "**Integration:** Hire items can be assigned to Events."
    ),
    "bi": (
        "The BI (Business Intelligence) module provides advanced analytics.\n\n"
        "**Features:**\n"
        "• Data visualization\n"
        "• Custom dashboards\n"
        "• Advanced reporting\n"
        "• Data export\n"
        "\n"
        "**Integration:** Analyzes data from all modules for strategic insights."
    )
}

