"""
SAS AI Report Generator - Creates downloadable reports.
"""
from sqlalchemy import func
from datetime import datetime, date
from flask import current_app
from sas_management.models import db
import os

# Safe model imports
try:
    from sas_management.models import InventoryItem, AccountingPayment, Invoice, Event, ProductionOrder
except Exception:
    InventoryItem = None
    AccountingPayment = None
    Invoice = None
    Event = None
    ProductionOrder = None


def generate_inventory_report() -> dict:
    """
    Generate inventory report.
    
    Returns:
        dict with report data and file path
    """
    if not InventoryItem:
        return {
            "success": False,
            "error": "Inventory module not available"
        }
    
    try:
        total_items = InventoryItem.query.count()
        low_stock = InventoryItem.query.filter(
            InventoryItem.stock_count <= 10
        ).count()
        
        # Get top categories
        categories = db.session.query(
            InventoryItem.category,
            func.count(InventoryItem.id).label('count')
        ).group_by(InventoryItem.category).all()
        
        report_data = {
            "title": "Inventory Report",
            "generated_at": datetime.now().isoformat(),
            "summary": f"Total items: {total_items}, Low stock: {low_stock}",
            "metrics": {
                "total_items": total_items,
                "low_stock_count": low_stock,
                "categories": {cat[0] or "Uncategorized": cat[1] for cat in categories}
            }
        }
        
        # Generate HTML report
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Inventory Report - SAS AI</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                h1 {{ color: #F6BC38; }}
                table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #F6BC38; color: #000; }}
            </style>
        </head>
        <body>
            <h1>Inventory Report</h1>
            <p><strong>Generated by SAS AI</strong></p>
            <p>Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            
            <h2>Summary</h2>
            <ul>
                <li>Total Items: {total_items}</li>
                <li>Low Stock Items: {low_stock}</li>
            </ul>
            
            <h2>Categories</h2>
            <table>
                <tr><th>Category</th><th>Item Count</th></tr>
        """
        
        for category, count in categories:
            html_content += f"<tr><td>{category or 'Uncategorized'}</td><td>{count}</td></tr>"
        
        html_content += """
            </table>
        </body>
        </html>
        """
        
        # Save report
        reports_dir = os.path.join(current_app.instance_path, "reports")
        os.makedirs(reports_dir, exist_ok=True)
        
        filename = f"inventory_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        filepath = os.path.join(reports_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return {
            "success": True,
            "report_url": f"/reports/{filename}",
            "report_data": report_data
        }
        
    except Exception as e:
        current_app.logger.error(f"Error generating inventory report: {e}", exc_info=True)
        return {
            "success": False,
            "error": f"⚠️ An error occurred while generating the report: {str(e)}"
        }


def generate_revenue_report() -> dict:
    """
    Generate revenue report.
    
    Returns:
        dict with report data and file path
    """
    if not AccountingPayment:
        return {
            "success": False,
            "error": "Accounting module not available"
        }
    
    try:
        total_payments = AccountingPayment.query.count()
        total_revenue = db.session.query(
            func.coalesce(func.sum(AccountingPayment.amount), 0)
        ).scalar() or 0
        
        # Get monthly breakdown
        monthly_data = db.session.query(
            func.strftime('%Y-%m', AccountingPayment.date).label('month'),
            func.sum(AccountingPayment.amount).label('total')
        ).group_by('month').order_by('month').all()
        
        report_data = {
            "title": "Revenue Report",
            "generated_at": datetime.now().isoformat(),
            "summary": f"Total revenue: {total_revenue:,.2f} UGX from {total_payments} payments",
            "metrics": {
                "total_revenue": float(total_revenue),
                "total_payments": total_payments,
                "monthly_breakdown": {m[0]: float(m[1]) for m in monthly_data}
            }
        }
        
        # Generate HTML report
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Revenue Report - SAS AI</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                h1 {{ color: #F6BC38; }}
                table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #F6BC38; color: #000; }}
            </style>
        </head>
        <body>
            <h1>Revenue Report</h1>
            <p><strong>Generated by SAS AI</strong></p>
            <p>Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            
            <h2>Summary</h2>
            <ul>
                <li>Total Revenue: {total_revenue:,.2f} UGX</li>
                <li>Total Payments: {total_payments}</li>
            </ul>
            
            <h2>Monthly Breakdown</h2>
            <table>
                <tr><th>Month</th><th>Revenue (UGX)</th></tr>
        """
        
        for month, amount in monthly_data:
            html_content += f"<tr><td>{month}</td><td>{float(amount):,.2f}</td></tr>"
        
        html_content += """
            </table>
        </body>
        </html>
        """
        
        # Save report
        reports_dir = os.path.join(current_app.instance_path, "reports")
        os.makedirs(reports_dir, exist_ok=True)
        
        filename = f"revenue_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        filepath = os.path.join(reports_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return {
            "success": True,
            "report_url": f"/reports/{filename}",
            "report_data": report_data
        }
        
    except Exception as e:
        current_app.logger.error(f"Error generating revenue report: {e}")
        return {
            "success": False,
            "error": str(e)
        }


def generate_performance_report() -> dict:
    """
    Generate overall performance report.
    
    Returns:
        dict with report data and file path
    """
    try:
        # Gather metrics from multiple modules
        metrics = {}
        
        if Event:
            metrics["total_events"] = Event.query.count()
        
        if Invoice:
            metrics["total_invoices"] = Invoice.query.count()
        
        if AccountingPayment:
            metrics["total_revenue"] = float(
                db.session.query(func.coalesce(func.sum(AccountingPayment.amount), 0)).scalar() or 0
            )
        
        if InventoryItem:
            metrics["total_inventory_items"] = InventoryItem.query.count()
        
        if ProductionOrder:
            metrics["active_production_orders"] = ProductionOrder.query.filter(
                ProductionOrder.status != "Completed"
            ).count()
        
        report_data = {
            "title": "Performance Report",
            "generated_at": datetime.now().isoformat(),
            "summary": "Overall system performance metrics",
            "metrics": metrics
        }
        
        # Generate HTML report
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Performance Report - SAS AI</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                h1 {{ color: #F6BC38; }}
                table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #F6BC38; color: #000; }}
            </style>
        </head>
        <body>
            <h1>Performance Report</h1>
            <p><strong>Generated by SAS AI</strong></p>
            <p>Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            
            <h2>Key Metrics</h2>
            <table>
                <tr><th>Metric</th><th>Value</th></tr>
        """
        
        for key, value in metrics.items():
            display_key = key.replace('_', ' ').title()
            if isinstance(value, float):
                display_value = f"{value:,.2f} UGX" if "revenue" in key.lower() else f"{value:,.2f}"
            else:
                display_value = str(value)
            html_content += f"<tr><td>{display_key}</td><td>{display_value}</td></tr>"
        
        html_content += """
            </table>
        </body>
        </html>
        """
        
        # Save report
        reports_dir = os.path.join(current_app.instance_path, "reports")
        os.makedirs(reports_dir, exist_ok=True)
        
        filename = f"performance_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        filepath = os.path.join(reports_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return {
            "success": True,
            "report_url": f"/reports/{filename}",
            "report_data": report_data
        }
        
    except Exception as e:
        current_app.logger.error(f"Error generating performance report: {e}")
        return {
            "success": False,
            "error": str(e)
        }

