"""Add RBAC models with inherit_from

Revision ID: b486e3a03516
Revises: 
Create Date: 2025-11-30 00:54:45.912010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b486e3a03516'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('permission')
    with op.batch_alter_table('bakery_item', schema=None) as batch_op:
        batch_op.drop_column('preparation_time')
        batch_op.drop_column('selling_price')
        batch_op.drop_column('cost_price')

    with op.batch_alter_table('dispatch_run', schema=None) as batch_op:
        batch_op.alter_column('run_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('floor_plan', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('layout_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text('\'{"objects": [], "meta": {"zoom"NULL,"pan":{"x"NULL,"y"NULL},"grid"NULL}}\''))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.drop_column('json_layout')
        batch_op.drop_column('layout_data')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_permissions_module'))
        batch_op.drop_column('module')
        batch_op.drop_column('action')

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('po_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('expected_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('items_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('order_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_unique_constraint(None, ['po_number'])
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inherit_from', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'roles', ['inherit_from'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('safety_incident', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'"))

    with op.batch_alter_table('seating_assignment', schema=None) as batch_op:
        batch_op.alter_column('floorplan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('guest_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('table_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'floor_plan', ['floorplan_id'], ['id'])
        batch_op.drop_column('floor_plan_id')

    with op.batch_alter_table('temperature_log', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('temperature_log', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('seating_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor_plan_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'floor_plan', ['floor_plan_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('table_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('guest_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('floorplan_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('safety_incident', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'"))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('inherit_from')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'permissions', ['permission_id'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('order_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('items_json')
        batch_op.drop_column('created_by')
        batch_op.drop_column('reference')
        batch_op.drop_column('expected_date')
        batch_op.drop_column('po_date')
        batch_op.drop_column('po_number')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('module', sa.VARCHAR(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_permissions_module'), ['module'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('floor_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout_data', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('json_layout', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('layout_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('\'{"objects": [], "meta": {"zoom"NULL,"pan":{"x"NULL,"y"NULL},"grid"NULL}}\''))
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('dispatch_run', schema=None) as batch_op:
        batch_op.alter_column('run_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('bakery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('(0.00)'), nullable=True))
        batch_op.add_column(sa.Column('selling_price', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('(0.00)'), nullable=True))
        batch_op.add_column(sa.Column('preparation_time', sa.INTEGER(), nullable=True))

    op.create_table('permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('module', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module')
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('permissions', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
